<style>
p {
  text-align: justify;  
  text-indent: 20px;   
}
</style> 

# Referências {-}

- <p>Global status report on road safety 2023. Geneva: World Health Organization; 2023. Licence: CC BY-NC-SA 3.0 IGO.

- <p>BRASIL. Ministério da Saúde. DATASUS - Departamento de Informática do SUS. Sistema de Informações sobre Mortalidade (SIM). 

- <p>Granieri, S.S., Reitano, E.E., Bindi, F.F. et al. Motorcycle-related trauma:effects of age and site of injuries on mortality. A single-center, retrospective study.. World J Emerg Surg 15, 18 (2020). https://doi.org/10.1186/s13017-020-00297-1 

- <p>Hidalgo-Fuentes S, Sospedra-Baeza MJ. Gender and age distribution of motorcycle crashes in Spain. Int J Inj Contr Saf Promot. 2019 Mar;26(1):108-114. doi: 10.1080/17457300.2018.1482927. Epub 2018 Sep 25. PMID: 30251597.  

- <p>Hsieh CH, Hsu SY, Hsieh HY, Chen YC. Differences between the sexes in motorcycle-related injuries and fatalities at a Taiwanese level I trauma center. Biomed J. 2017 Apr;40(2):113-120. doi: 10.1016/j.bj.2016.10.005. Epub 2017 May 4. PMID: 28521902; PMCID: PMC6138601.

- <p>Shabadin, Akmalia & Jamil, Hawa. (2015). GENDER AND AGE DIFFERENCES IN TRAVEL PATTERN AND ROAD CRASHES AMONG MOTORCYCLIST IN SELANGOR. 

- <p>Barzegar, A. *et al*. Epidemiologic study of traffic crash mortality among motorcycle users in Iran (2011-2017). Elsevier. Chinese Journal of Traumatology 23, 2020.

- <p>Almeida GCM, Medeiros FCD, Pinto LO, Moura JMBO, Lima KC. Prevalence and factors associated with traffic accidents involving motorcycle taxis. Rev Bras Enferm [Internet]. 2016;69(2):359-65. DOI: http://dx.doi.org/10.1590/0034-7167.2016690223i.

- <p>Shaker, R.H., Eldesouky, R.S., Hasan, O.M. *et al.* Motorcycle Crashes: Attitudes of the Motorcyclists Regarding Riders’ Experience and Safety Measures. J Community Health 39, 1222–1230 (2014). https://doi.org/10.1007/s10900-014-9883-1

- <p>Chaves, M. *et al*. MOTORCYCLE ACCIDENTS: PROFILE AND CHARACTERIZATION OF VICTIMS ASSISTED IN A PUBLIC HOSPITAL. Journal of Nursing, 2015.

- <p>Crompton JG, Pollack KM, Oyetunji T, Chang DC, Efron DT, Haut ER, Cornwell EE 3rd, Haider AH. Racial disparities in motorcycle-related mortality: an analysis of the National Trauma Data Bank. Am J Surg. 2010 Aug;200(2):191-6. doi: 10.1016/j.amjsurg.2009.07.047. PMID: 20678618.

- <p>Souza, R. *et al*. (2020). Race and Mortality in Motorcycle Accidents in Brazil. 